version: 2.1
orbs:
  cypress: cypress-io/cypress@1.13.0
workflows:
  build:
    jobs:
      - cypress/run:
          post-steps:
            - store_test_results:
                path: cypress/results