version: 2
jobs:
  node:
    working_directory: ~/picker
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout

      - run: npm install

      - run:
          name: run user acceptance tests
          command: npm run cy:run